services:
    backend:
        build:
            context: ./src/services/FactCheckBack
            dockerfile: ./FactCheckBack.API/Dockerfile
        ports:
            - '5001:8080'
        environment:
            # ASP.NET Core host
            ASPNETCORE_URLS: http://0.0.0.0:8080

            # CORS (dominio del frontend)
            AllowedOrigins: ${FRONTEND_ORIGIN}

            # ===== AppSettings via ENV (formato con __ para binding) =====
            # JWT
            JWT__SecretKey: ${JWT_SECRET_KEY}
            JWT__Issuer: FactCheckAPI
            JWT__Audience: FactCheckClient
            JWT__ExpirationTimeMinutes: ${JWT_EXP_MINUTES}

            # Logging
            Logging__LogLevel__Default: Information
            Logging__LogLevel__Microsoft__AspNetCore: Warning

            # ConnectionStrings
            ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}

            # Google OAuth
            Authentication__Google__ClientId: ${AUTH_GOOGLE_ID}
            Authentication__Google__ClientSecret: ${AUTH_GOOGLE_SECRET}

            # Servicio de IA
            AiApi__Url: ${AI_API_URL}
        depends_on:
            - iamodel

    iamodel:
        build:
            context: ./src/services/AIModel
        ports:
            - '5002:8080'
        environment:
            PORT: 8080
            # CORS: origen del frontend
            ALLOWED_ORIGINS: ${FRONTEND_ORIGIN}

            # ===== Variables de IA =====
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            MODEL: ${OPENAI_MODEL}
            PROMPT: ${OPENAI_PROMPT}
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
            interval: 10s
            timeout: 3s
            retries: 2

    frontend:
        build:
            context: ./src/frontend/factchecker-front
            args:
                APP_NAME: ${APP_NAME}
                APP_DESCRIPTION: ${APP_DESCRIPTION}
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        ports:
            - '3000:8080'
        environment:
            AUTH_URL: ${AUTH_URL}
            AUTH_REDIRECT_PROXY_URL: ${AUTH_REDIRECT_PROXY_URL}
            AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
            AUTH_SECRET: ${AUTH_SECRET}
            AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
            AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
            GOOGLE_ID: ${GOOGLE_ID}
            GOOGLE_SECRET: ${GOOGLE_SECRET}
            NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
            API_URL_INTERNAL: ${API_URL_INTERNAL}
        depends_on:
            - backend
